#!/usr/bin/env bash

brew install caskroom/cask/brew-cask

brew cask install \
  1password \
  acorn \
  aerial \
  alfred \
  amethyst \
  bartender \
  charles \
  choosy \
  chromedriver \
  contexts \
  daisydisk \
  dash \
  docker \
  figma \
  firefox \
  google-chrome \
  google-cloud-sdk \
  grammarly \
  hyperdock \
  iina \
  imageoptim \
  itsycal \
  karabiner-elements \
  keka \
  kitty \
  monitorcontrol \
  monodraw \
  ngrok \
  numi \
  paw \
  postbox \
  postico \
  qmoji \
  skype \
  spotify \
  sublime-merge \
  telegram \
  textual \
  tower \
  transmission \
  visual-studio-code \
  zoomus

# fonts
brew tap caskroom/fonts
brew cask install font-iosevka

# quicklool plugins
brew cask install \
  epubquicklook \
  qlcolorcode \
  qlimagesize \
  qlmarkdown \
  qlprettypatch \
  qlstephen \
  qlvideo \
  quicklook-csv \
  quicklook-json \
  webpquicklook

brew cleanup -s
