#!/usr/bin/env bash

brew install \
  ack \
  ansible \
  ansible-lint \
  asciinema \
  asdf \
  aspell \
  bat \
  brotli \
  broot \
  clang-format \
  coreutils \
  diff-so-fancy \
  direnv \
  docker-clean \
  exa \
  ffmpeg \
  fish \
  fontconfig \
  fzf \
  gifsicle \
  git \
  git-extras \
  git-lfs \
  git-sizer \
  hub \
  jq \
  media-info \
  moreutils \
  ncdu \
  ninja \
  overmind \
  reattach-to-user-namespace \
  starship \
  tldr \
  tmux \
  tree  \
  wget

# init git-lfs
git lfs install
