#+TITLE:      Wayland (Sway) configuration
#+AUTHOR:     Vitaly Slobodin
#+PROPERTY:   header-args+ :comments both :mkdirp yes

* Contents :TOC:
- [[#sway][Sway]]
  - [[#include-host-specific-configuration][Include host-specific configuration]]
  - [[#set-key-modifier][Set key modifier]]
  - [[#set-terminal-emulator][Set terminal emulator]]
  - [[#set-application-launcher][Set application launcher]]
  - [[#set-font][Set font]]
  - [[#disable-xwayland][Disable xwayland]]
  - [[#configure-output][Configure output]]
  - [[#configure-input][Configure input]]
  - [[#gaps][Gaps]]
  - [[#set-cursor-theme][Set cursor theme]]
  - [[#key-bindings][Key bindings]]
  - [[#workspaces][Workspaces]]
  - [[#modes][Modes]]
  - [[#bar][Bar]]
  - [[#startup][Startup]]
- [[#status-bar][Status Bar]]
  - [[#i3status-rust][i3status-rust]]
- [[#swaylock][swaylock]]
- [[#mako][mako]]
- [[#wofi][wofi]]
- [[#foot][foot]]
  - [[#configuration][Configuration]]
- [[#scripts][Scripts]]
  - [[#starting-sway][Starting sway]]

* Sway
:PROPERTIES:
:header-args: :tangle "~/.config/sway/config" :mkdirp yes
:END:
** Include host-specific configuration
#+begin_src conf
include $HOME/.config/sway/$(hostname)/*.conf
#+end_src
** Set key modifier
Set key modifier to Super
#+begin_src conf
set $mod Mod4
#+end_src
** Set terminal emulator
#+begin_src conf
set $term kitty
#+end_src
** Set application launcher
#+begin_src conf
set $menu dmenu_path | wofi --show drun | xargs swaymsg exec --
#+end_src
** Set font
Font for window titles. Will also be used by the bar unless a different font
is used in the bar {} block below.
#+begin_src conf
font pango:sanf-serif 14
#+end_src
** Disable xwayland
#+begin_src conf
xwayland disable
#+end_src
** Configure output
#+begin_src conf :tangle ~/.config/sway/serenity/02_output.conf
output eDP-1 {
  subpixel rgb
  scale 1.5
}
#+end_src

#+begin_src conf :tangle ~/.config/sway/firefly/02_output.conf
output DP-1 {
  subpixel rgb
  scale 1.25
}
#+end_src
** Configure input
*** Common
#+begin_src conf :tangle ~/.config/sway/config
input type:keyboard {
  xkb_layout "us,ru"
  xkb_options "grp:alt_space_toggle,caps:ctrl_modifier"
  repeat_delay 210
  repeat_rate 40
}
#+end_src
*** Serenity
Touchpad configuration.
#+begin_src conf :tangle ~/.config/sway/serenity/03_input.conf
input type:touchpad {
  accel_profile adaptive
  drag enabled
  dwt enabled
  natural_scroll enabled
  tap enabled
  tap_button_map lrm
}
#+end_src
** Gaps
#+begin_src conf :tangle ~/.config/sway/config
set $inner_gaps 8
set $outer_gaps 12

gaps inner $inner_gaps
gaps outer $outer_gaps
smart_gaps on
smart_borders on
#+end_src
** Set cursor theme
#+begin_src conf :tangle ~/.config/sway/config
seat seat0 xcursor_theme capitaine-cursors 32
#+end_src
** Key bindings
Use ~Mouse+$mod~ to drag floating windows to their wanted position.
#+begin_src conf :tangle ~/.config/sway/config
floating_modifier $mod normal
#+end_src
Start a terminal.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+Return exec $term
#+end_src
Kill focused window.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+q kill
#+end_src
Start dmenu (a program launcher).
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+d exec $menu
#+end_src
Change focus.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
#+end_src
Move focused window.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
#+end_src
Split in horizontal orientation.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+c split horizontal
#+end_src
Split in vertical orientation.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+v split vertical
#+end_src
Enter fullscreen mode for the focused container.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+f fullscreen toggle
#+end_src
Change container layout (stacked, tabbed, toggle split).
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
#+end_src
Toggle tiling / floating,
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+Shift+space floating toggle
#+end_src
Change focus between tiling / floating windows.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+space focus mode_toggle
#+end_src
Focus the parent container.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+a focus parent
#+end_src
Focus the child container.
#+begin_src conf :tangle no
bindsym $mod+d focus child
#+end_src
Printscreen.
#+begin_src conf :tangle no
bindsym --release Print exec --no-startup-id flameshot gui
#+end_src
Media Keys.
#+begin_src conf :tangle ~/.config/sway/config
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindsym XF86AudioPlay exec playerctl play-pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous
#+end_src
** Workspaces
Define names for default workspaces for which we configure key bindings later on. We use variables to avoid repeating the names in multiple places.

#+begin_src conf :tangle ~/.config/sway/config
set $ws1 "1:web"
set $ws2 "2:term"
set $ws3 "3:work"
set $ws4 "4:dev"
set $ws5 "5:social"
set $ws6 "6:meeting"
set $ws7 "7:music"
set $ws8 "8:video"
set $ws9 "9:streaming"
#+end_src

Switch to workspace.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
#+end_src

Move focused container to workspace.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
#+end_src

Switch to previous/next workspace.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+bracketleft workspace prev
bindsym $mod+bracketright workspace next
#+end_src

Reload the configuration file.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+Shift+c reload
#+end_src

Restart sway inplace.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+Shift+r restart
#+end_src

Shortcut to exit sway
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+Shift+e exec swaynag -t warning -m \
  'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' \
   -b 'Yes, exit sway' 'swaymsg exit'
#+end_src
*** Assign applications to workspaces
Brave -> Workspace 1
#+begin_src conf :tangle ~/.config/sway/config
assign [class="Brave"] $ws1
#+end_src

Slack -> Workspace 3
#+begin_src conf :tangle ~/.config/sway/config
assign [class="Slack"] $ws3
#+end_src

Telegram -> Workspace 5
#+begin_src conf :tangle ~/.config/sway/config
assign [class="TelegramDesktop"] $ws5
#+end_src

Spotify -> Workspace 7
#+begin_src conf :tangle ~/.config/sway/config
assign [class="spotify"] $ws7
#+end_src
*** Additional rules for the applications or windows
Zoom.
#+begin_src conf :tangle ~/.config/sway/config
# For pop up notification windows that don't use notifications api
for_window [app_id="zoom" title="^zoom$"] border none, floating enable
# For specific Zoom windows
for_window [app_id="zoom" title="^(Zoom|About)$"] border pixel, floating enable
for_window [app_id="zoom" title="Settings"] floating enable, floating_minimum_size 960 x 700
# for_window [class = "^Zoom$"] floating enable
# for_window [app_id = "zoom"] floating enable
#+end_src
** Modes
*** Resize
Mode for resizing containers.
#+begin_src conf :tangle ~/.config/sway/config
bindsym $mod+r mode "resize"

mode "resize" {
  # These bindings trigger as soon as you enter the resize mode

  # Pressing left will shrink the window’s width.
  # Pressing right will grow the window’s width.
  # Pressing up will shrink the window’s height.
  # Pressing down will grow the window’s height.
  bindsym h       resize shrink width 10 px or 10 ppt
  bindsym j       resize grow height 10 px or 10 ppt
  bindsym k       resize shrink height 10 px or 10 ppt
  bindsym l       resize grow width 10 px or 10 ppt

  # same bindings, but for the arrow keys
  bindsym Left        resize shrink width 10 px or 10 ppt
  bindsym Down        resize grow height 10 px or 10 ppt
  bindsym Up          resize shrink height 10 px or 10 ppt
  bindsym Right       resize grow width 10 px or 10 ppt

  # back to normal: Enter or Escape or Mod1+r
  bindsym Return mode "default"
  bindsym Escape mode "default"
  bindsym $mod+r mode "default"
}
#+end_src
** Bar
Simple bar with default colors.
#+begin_src conf :tangle ~/.config/sway/config
bar {
  position top
  status_padding 0
  strip_workspace_numbers yes
  status_command i3status-rs

  tray {
    tray_padding 2
    icon_theme   Papirus-Dark
  }
}
#+end_src
** Startup
*** Import environment
#+begin_src conf :tangle ~/.config/sway/config
exec_always systemctl --user import-environment
#+end_src
*** Activate DBus environment
#+begin_src conf :tangle ~/.config/sway/config
exec dbus-update-activation-environment --systemd --all
#+end_src
*** Notification daemon
#+begin_src conf :tangle ~/.config/sway/config
exec mako
#+end_src
*** Foot server
Disabled because I use ~kitty~.
#+begin_src conf :tangle no
exec foot -s
#+end_src
*** Autorun applications.
#+begin_src conf :tangle ~/.config/sway/config
exec dex -a
#+end_src
*** GNOME Polkit
#+begin_src conf :tangle ~/.config/sway/config
exec_always /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#+end_src
*** Background
#+begin_src conf :tangle ~/.config/sway/config
exec_always swaybg -m fill -i $HOME/Pictures/wallpaper.jpg
#+end_src
*** GTK settings
#+begin_src conf :tangle ~/.config/sway/config
set $gnome-schema org.gnome.desktop.interface

exec_always {
  gsettings set $gnome-schema cursor-theme 'capitaine-cursors'
  gsettings set $gnome-schema font-name 'sans-serif 11'
  gsettings set $gnome-schema font-antialiasing 'rgba'
}
#+end_src
* Status Bar
** i3status-rust
#+begin_src conf :tangle ~/.config/i3status-rust/config.toml
theme = "native"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "sound"

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^10} {strength}"
device_format = "{icon}{ap}"

[[block]]
block = "keyboard_layout"
driver = "sway"
interval = 15

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
#+end_src
* swaylock
#+begin_src conf :tangle ~/.config/swaylock/config
daemonize

ignore-empty-password

fade-in=0.1

# color=000000
screenshots
effect-blur=7x5
effect-vignette=0.5:0.5

indicator

clock
datestr=%Y-%m-%d (%a)
#+end_src
* mako
#+begin_src conf :tangle ~/.config/mako/config
font=sans-serif 14
default-timeout=5000
ignore-timeout=1
width=300
#+end_src
* wofi
#+begin_src conf :tangle ~/.config/wofi/config
allow_markup=true
lines=10
width=25%
key_up=Control_L-k
key_down=Control_L-j
#+end_src

#+begin_src css :tangle ~/.config/wofi/style.css
window {
  border-radius: 0px;
}

#input {
  border-radius: 0px;
}
#+end_src
* foot
:PROPERTIES:
:header-args: :tangle "~/.config/foot/foot.ini" :mkdirp yes
:END:
** Configuration
Set font.
#+begin_src conf
font=monospace term:size=12, Noto Color Emoji:size=10
#+end_src

Draw bold text in bright.
#+begin_src conf
bold-text-in-bright=yes
#+end_src
*** Theme and colors
**** Modus Operandi
#+begin_src conf
[cursor]
color=ffffff 4a484d

[colors]
background= ffffff
foreground= 000000

regular0=   000000
regular1=   a60000
regular2=   005e00
regular3=   813e00
regular4=   0031a9
regular5=   721045
regular6=   00538b
regular7=   bfbfbf

bright0=    595959
bright1=    972500
bright2=    315b00
bright3=    70480f
bright4=    2544bb
bright5=    5317ac
bright6=    005a5f
bright7=    ffffff
#+end_src
* Scripts
** Starting sway
#+begin_src sh :tangle ~/.local/bin/start-sway :shebang "#!/usr/bin/env sh"
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND=wayland

export QT_QPA_PLATFORM=wayland-egl
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_WAYLAND_FORCE_DPI=111

export ECORE_EVAS_ENGINE=wayland-egl
export ELM_ENGINE=wayland_egl
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export NO_AT_BRIDGE=1

systemd-cat --identifier=sway sway $@
#+end_src
