#+TITLE:      X11 Configuration
#+AUTHOR:     Vitaly Slobodin
#+PROPERTY:   header-args+ :mkdirp yes :noweb yes :eval no

* Contents :TOC:
- [[#x11-configuration][X11 configuration]]
- [[#i3][i3]]
  - [[#set-key-modifier][Set key modifier]]
  - [[#set-font][Set font]]
  - [[#key-bindings][Key bindings]]
  - [[#workspaces][Workspaces]]
  - [[#modes][Modes]]
  - [[#windows-settings-for-various-applications][Windows settings for various applications]]
  - [[#bar][Bar]]
  - [[#startup][Startup]]
- [[#i3status][i3status]]
  - [[#general][General]]
  - [[#blocks-order][Blocks order]]
  - [[#blocks-configuration][Blocks configuration]]
- [[#rofi][rofi]]
  - [[#configuration][Configuration]]
- [[#feh][feh]]
- [[#dunst][dunst]]
- [[#picom][Picom]]
- [[#kitty][kitty]]
  - [[#fonts][Fonts]]
  - [[#performance-tuning][Performance tuning]]
  - [[#tab-bar][Tab bar]]
  - [[#advanced][Advanced]]
  - [[#os-specific-settings][OS specific settings]]
  - [[#key-bindings-1][Key bindings]]
  - [[#theme][Theme]]

* X11 configuration
Add system configurations for X11.
#+begin_src conf :tangle no
Section "Monitor"
  Identifier             "<default monitor>"
  DisplaySize            878.11 485.35
EndSection
#+end_src

#+begin_src conf :tangle no
Section "Device"
  Identifier "AMD"
  Driver "amdgpu"
  Option "TearFree" "true"
EndSection
#+end_src

#+begin_src sh :tangle ~/.Xresources
Xcursor.theme:  phinger-cursors
Xcursor.size:   42

Xft.dpi:        153
Xft.antialias:  true
Xft.rgba:       none
Xft.hinting:    true
Xft.hintstyle:  hintslight
Xft.autohint:   0
#+end_src
* i3
** Set key modifier
Set key modifier to Super
#+begin_src conf :tangle ~/.config/i3/config
set $mod Mod4
#+end_src

** Set font
Font for window titles. Will also be used by the bar unless a different font
is used in the bar {} block below.
#+begin_src conf :tangle ~/.config/i3/config
font pango:sans-serif 12
#+end_src

** Key bindings
Use =Mouse+$mod= to drag floating windows to their wanted position.
#+begin_src conf :tangle ~/.config/i3/config
floating_modifier $mod
#+end_src

Start a terminal.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+Return exec i3-sensible-terminal
#+end_src

Kill focused window.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+q kill
#+end_src

Start dmenu (a program launcher).
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+d exec --no-startup-id rofi -show drun
bindsym $mod+Tab exec --no-startup-id rofi -show window
#+end_src

Run ~emacs-anywhere~.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+Ctrl+e exec --no-startup-id ~/.emacs.d/bin/doom everywhere
#+end_src

Change focus.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
#+end_src

Move focused window.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
#+end_src

Split in horizontal orientation.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+c split horizontal
#+end_src

Split in vertical orientation.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+v split vertical
#+end_src

Enter fullscreen mode for the focused container.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+f fullscreen toggle
#+end_src

Change container layout (stacked, tabbed, toggle split).
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
#+end_src

Toggle tiling / floating,
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+Shift+space floating toggle
#+end_src

Change focus between tiling / floating windows.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+space focus mode_toggle
#+end_src

Focus the parent container.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+a focus parent
#+end_src

Focus the child container.
#+begin_src conf :tangle no
bindsym $mod+d focus child
#+end_src

Printscreen.
#+begin_src conf :tangle ~/.config/i3/config
bindsym --release Print exec --no-startup-id flameshot gui
#+end_src

Media Keys.
#+begin_src conf :tangle ~/.config/i3/config
bindsym XF86AudioPlay exec playerctl play
bindsym XF86AudioPause exec playerctl pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous
#+end_src

i3 volume integration
#+begin_src conf :tangle ~/.config/i3/config
## Volume control

# Command for the status line
#   ie: i3blocks, i3status
set $statuscmd i3status

# Signal used to update the status line
#   i3blocks uses SIGRTMIN+10 by default
#   i3status uses SIGUSR1 by default
set $statussig SIGUSR1

# Amount to increase/decrease volume as a percentage
set $volumestep 5

# pulseaudio-utils settings
#
# Symbolic name for sink (numeric index not supported)
#   Recommended: comment out this setting and omit the -s option to use default sink
#   List sink names: pacmd list-sinks | awk -F "[<>]" '/^\s+name: <.*>/{print $2}'
#set $sinkname alsa_output.pci-0000_00_1b.0.analog-stereo

# Using pulseaudio-utils (append "-s $sinkname" without quotes to override default sink)
bindsym XF86AudioRaiseVolume exec --no-startup-id i3-volume -n -t $statuscmd -u $statussig up $volumestep -N dunst
bindsym XF86AudioLowerVolume exec --no-startup-id i3-volume -n -t $statuscmd -u $statussig down $volumestep -N dunst
bindsym XF86AudioMute        exec --no-startup-id i3-volume -n -t $statuscmd -u $statussig mute
#+end_src

** Workspaces
Define names for default workspaces for which we configure key bindings later on. We use variables to avoid repeating the names in multiple places.
#+begin_src conf :tangle ~/.config/i3/config
set $ws1 "1:web"
set $ws2 "2:term"
set $ws3 "3:work"
set $ws4 "4:dev"
set $ws5 "5:social"
set $ws6 "6:meeting"
set $ws7 "7:music"
set $ws8 "8:video"
set $ws9 "9:streaming"
#+end_src

Switch to workspace.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
#+end_src

Move focused container to workspace.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
#+end_src

Switch to previous/next workspace.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+bracketleft workspace prev
bindsym $mod+bracketright workspace next
#+end_src

Reload the configuration file.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+Shift+c reload
#+end_src

Restart i3 inplace (preserves layout/session, can be used to upgrade i3).
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+Shift+r restart
#+end_src

Gaps.
#+begin_src conf :tangle ~/.config/i3/config
set $inner_gaps 4
set $outer_gaps 12

gaps inner $inner_gaps
gaps outer $outer_gaps
smart_gaps on
smart_borders on
#+end_src

*** Assign applications to workspaces
Brave -> Workspace 1
#+begin_src conf :tangle ~/.config/i3/config
assign [class="Brave"] $ws1
#+end_src

Slack -> Workspace 3
#+begin_src conf :tangle ~/.config/i3/config
assign [class="Slack"] $ws3
#+end_src

Telegram -> Workspace 5
#+begin_src conf :tangle ~/.config/i3/config
assign [class="TelegramDesktop"] $ws5
#+end_src

Spotify -> Workspace 7
#+begin_src conf :tangle ~/.config/i3/config
assign [class="spotify"] $ws7
#+end_src

*** Additional rules for the applications or windows
Let =emacs-anywhere= float.
#+begin_src conf :tangle ~/.config/i3/config
for_window [class="emacs-anywhere"] floating enable
#+end_src

** Modes
*** Resize
Mode for resizing containers.
#+begin_src conf :tangle ~/.config/i3/config
bindsym $mod+r mode "resize"

mode "resize" {
  # These bindings trigger as soon as you enter the resize mode

  # Pressing left will shrink the window’s width.
  # Pressing right will grow the window’s width.
  # Pressing up will shrink the window’s height.
  # Pressing down will grow the window’s height.
  bindsym h       resize shrink width 10 px or 10 ppt
  bindsym j       resize grow height 10 px or 10 ppt
  bindsym k       resize shrink height 10 px or 10 ppt
  bindsym l       resize grow width 10 px or 10 ppt

  # same bindings, but for the arrow keys
  bindsym Left        resize shrink width 10 px or 10 ppt
  bindsym Down        resize grow height 10 px or 10 ppt
  bindsym Up          resize shrink height 10 px or 10 ppt
  bindsym Right       resize grow width 10 px or 10 ppt

  # back to normal: Enter or Escape or Mod1+r
  bindsym Return mode "default"
  bindsym Escape mode "default"
  bindsym $mod+r mode "default"
}
#+end_src

*** System
Mode for shut down, restart and locking features.
#+begin_src conf :tangle ~/.config/i3/config
set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Ctrl+s) shutdown

mode "$mode_system" {
  bindsym l exec --no-startup-id xsecurelock, mode "default"
  bindsym e exec --no-startup-id i3-msg exit, mode "default"
  bindsym s exec --no-startup-id $i3lockwall && systemctl suspend, mode "default"
  bindsym h exec --no-startup-id $i3lockwall && systemctl hibernate, mode "default"
  bindsym r exec --no-startup-id systemctl reboot, mode "default"
  bindsym Ctrl+s exec --no-startup-id systemctl poweroff -i, mode "default"

  # back to normal: Enter or Escape
  bindsym Return mode "default"
  bindsym Escape mode "default"
}

bindsym $mod+BackSpace mode "$mode_system"
#+end_src

** Windows settings for various applications
Make =Pavucontrol= float around.
#+begin_src conf :tangle ~/.config/i3/config
for_window [class="Pavucontrol"] floating enable
#+end_src

Fix size and position of the GTK File Choose Dialog.
#+begin_src conf :tangle ~/.config/i3/config
for_window [window_role="GtkFileChooserDialog"] resize set 1024 768
for_window [window_role="GtkFileChooserDialog"] move position center
#+end_src

Make Zoom popups float.
#+begin_src conf :tangle no
for_window [class="zoom"] floating enable
#+end_src
#+end_src
** Bar
~i3status~ configuration.
#+begin_src conf :tangle ~/.config/i3/config
bar {
  status_command i3status
  position top
  strip_workspace_numbers yes
}
#+end_src
** Startup
Screen locking with =xss-lock=. =xss-lock= grabs a =logind= suspend inhibit lock and will use [[https://github.com/google/xsecurelock][xsecurelock]] to lock the screen before suspend. Use =loginctl lock-session= to lock your screen.
#+begin_src conf :tangle ~/.config/i3/config
exec --no-startup-id xss-lock --transfer-sleep-lock -- xsecurelock --nofork
#+end_src

Increase a typematic delay to 210ms and a typematic rate to 40Hz.
#+begin_src conf :tangle ~/.config/i3/config
exec --no-startup-id xset r rate 210 40
#+end_src

Solaar for a Logitech mouse.
#+begin_src conf :tangle no
exec --no-startup-id solaar --window=hide
#+end_src

Picom.
#+begin_src conf :tangle ~/.config/i3/config
exec --no-startup-id picom --experimental-backends -b
#+end_src

udiskie.
#+begin_src conf :tangle ~/.config/i3/config
exec --no-startup-id udiskie -t
#+end_src

Autorun applications.
#+begin_src conf :tangle ~/.config/i3/config
exec --no-startup-id dex -a
#+end_src

Set keyboard layout.
#+begin_src conf :tangle ~/.config/i3/config
exec --no-startup-id setxkbmap -layout us,ru -option 'grp:alt_shift_toggle,caps:ctrl_modifier'
#+end_src

Background.
#+begin_src conf :tangle ~/.config/i3/config
exec --no-startup-id $HOME/.fehbg
#+end_src

* i3status
** General
Update the bar each 5 seconds.
#+begin_src conf :tangle ~/.config/i3status/config
general {
  interval = 5
  colors = true
}
#+end_src
** Blocks order
#+begin_src conf :tangle ~/.config/i3status/config
order += "cpu_usage"
order += "memory"
order += "tztime local"
#+end_src
** Blocks configuration
*** CPU Usage
#+begin_src conf :tangle ~/.config/i3status/config
cpu_usage {
  format = " %usage"
}
#+end_src
*** CPU Temperature
#+begin_src conf :tangle ~/.config/i3status/config
cpu_temperature 0 {
  format ="%degrees°C"
  max_threshold = 75
  path = "/sys/devices/platform/nct6775.656/hwmon/hwmon4/temp2_input"
}
#+end_src
*** Memory
#+begin_src conf :tangle ~/.config/i3status/config
memory {
  format = " %used"
  threshold_degraded = "1G"
  format_degraded = "MEMORY < %available"
}
#+end_src
*** Date and Time
#+begin_src conf :tangle ~/.config/i3status/config
tztime local {
  format = " %Y-%m-%d %H:%M"
}
#+end_src
* rofi
** Configuration
#+begin_src conf :tangle "~/.config/rofi/config.rasi"
configuration {
  dpi: 153;
  icon-theme: "Papirus-Dark";
  modi: "drun,ssh";
  show-icons: true;
  terminal: "kitty";
  run-command: "fish -c '{cmd}'";
  display-run: "=>";
  display-ssh: "~>";
  display-drun: "::";
  kb-move-front: "Control+a";
  kb-move-end: "Control+e";
  kb-move-word-back: "Control+Left";
  kb-move-word-forward: "Control+Right";
  kb-move-char-back: "Left";
  kb-move-char-forward: "Right";
  kb-remove-to-eol: "Control+f";
  kb-remove-to-sol: "Control+b";
  kb-accept-entry: "Control+m,Return,KP_Enter";
  kb-row-up: "Control+k,Up";
  kb-row-down: "Control+j,Down";
}
#+end_src
* feh
Set VIM-like keybindings.
#+begin_src sh :tangle ~/.config/feh/keys
# Vim like keybindings

menu_parent   Left
menu_child    Right
menu_down     Down
menu_up       Up

scroll_left   h
scroll_right  l
scroll_up     k
scroll_down   j

scroll_left_page      C-h
scroll_right_page     C-l
scroll_up_page        C-k
scroll_down_page      C-j

toggle_aliasing       A
toggle_filenames      d
toggle_pointer        o
toggle_fullscreen     f

zoom_in               plus
zoom_out              minus

next_img              greater
prev_img              less
reload_image          r
size_to_image         w
next_dir              bracketright
prev_dir              bracketleft
orient_3              parenright
orient_1              parenleft
flip                  underscore
mirror                bar
remove                Delete
zoom_fit              s
zoom_default          a

close                 q Q
#+end_src
* dunst
Notification daemon.

#+begin_src conf :tangle ~/.config/dunst/dunstrc
[global]
alignment = left
bounce_freq = 0
browser = firefox -new-tab
corner_radius = 2
dmenu = rofi -dmenu -p dunst:
follow = none
font = sans-serif 12
format = "<b>%s</b>\n%b"
frame_color = "#282a36"
frame_width = 1
# geometry [{width}]x{height}][+/-{x}+/-{y}]
geometry = "440x15-26+26"
history_length = 20
horizontal_padding = 16
icon_position = right
idle_threshold = 120
ignore_newline = no
indicate_hidden = yes
line_height = 0
markup = full
max_icon_size = 64
monitor = 0
padding = 20
separator_color = auto
separator_height = 4
show_age_threshold = 60
show_indicators = yes
shrink = no
sort = yes
startup_notification = false
sticky_history = yes
transparency = 5
word_wrap = yes
#+end_src

* Picom
#+begin_quote
Composing manager.
#+end_quote

#+begin_src conf :tangle ~/.config/picom/picom.conf
# Specify the backend to use: `xrender`, `glx`, or `xr_glx_hybrid`.
# `xrender` is the default one.
backend = "glx";

# Avoid using stencil buffer, may increase performance
glx-no-stencil = true;

# Enable/disable VSync.
vsync = true;

# Use X Sync fence to sync clients' draw calls, to make sure all draw
# calls are finished before picom starts drawing. Needed on nvidia-drivers
# with GLX backend for some users.
xrender-sync-fence = true;

glx-copy-from-front = false;
glx-no-rebind-pixmap = true;
use-damage = true;

# Enabled client-side shadows on windows. Note desktop windows
# (windows with '_NET_WM_WINDOW_TYPE_DESKTOP') never get shadow,
# unless explicitly requested using the wintypes option.
shadow = true;

# The blur radius for shadows. (default 12)
shadow-radius = 7;
# The left offset for shadows. (default -15)
shadow-offset-x = -5;
# The top offset for shadows. (default -15)
shadow-offset-y = -5;
# The translucency for shadows. (default .75)
shadow-opacity = 0.8;

# Specify a list of conditions of windows that should have no shadow.
shadow-exclude = [
  # Put shadows on notifications, the scratch popup and rofi only
  "! name~='(rofi|scratch|Dunst)$'"
];

# Fade windows in/out when opening/closing and when opacity changes,
# unless no-fading-openclose is used.
fading = true;

# Opacity change between steps while fading in. (0.01 - 1.0, defaults to 0.028)
fade-in-step = 0.01;

# Opacity change between steps while fading out. (0.01 - 1.0, defaults to 0.03)
fade-out-step = 0.012;

# The time between steps in fade step, in milliseconds. (> 0, defaults to 10)
fade-delta = 1;

detect-client-opacity = true;
inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
opacity-rule = [
  # "100:class_g = 'Firefox'"
  "100:class_g = 'VirtualBox Machine'",
  # Art/image programs where we need fidelity
  "100:class_g = 'Gimp'",
  "100:class_g = 'Inkscape'",
  "100:class_g = 'feh'",
  "100:class_g = 'mpv'",
  "80:class_g = 'Rofi'",
  "90:class_g = 'kitty'",
  "99:_NET_WM_STATE@:32a = '_NET_WM_STATE_FULLSCREEN'"
]

blur: {
  method           = "dual_kawase";
  strength         = 2;
  background       = true;
  background-frame = true;
  background-fixed = true;
}

wintypes: {
  normal = { blue-background = true; };
  splash = { blur-background = false; };
}
#+end_src

* kitty
:PROPERTIES:
:header-args: :tangle "~/.config/kitty/kitty.conf" :mkdirp yes
:END:
** Fonts
Setup font and its size.
#+begin_src conf
font_family monospace term
font_size   11.0
#+end_src
** Performance tuning
Sync screen updates to the refresh rate of the monitor. This
prevents tearing (https://en.wikipedia.org/wiki/Screen_tearing)
when scrolling. However, it limits the rendering speed to the
refresh rate of your monitor. With a very high speed mouse/high
keyboard repeat rate, you may notice some slight input latency. If
so, set this to no.
#+begin_src conf
sync_to_monitor yes
#+end_src

The width (in pts) of window borders. Will be rounded to the
nearest number of pixels based on screen resolution. Note that
borders are displayed only when more than one window is visible.
They are meant to separate multiple windows.
#+begin_src conf
window_border_width 0.0
#+end_src

Draw only the minimum borders needed. This means that only the
minimum needed borders for inactive windows are drawn. That is only
the borders that separate the inactive window from a neighbor. Note
that setting a non-zero window margin overrides this and causes all
borders to be drawn.
#+begin_src conf
draw_minimal_borders yes
#+end_src

The window padding (in pts) (blank area between the text and the
window border)
#+begin_src conf
window_padding_width 0.0
#+end_src

When the window size is not an exact multiple of the cell size, the
cell area of the terminal window will have some extra padding on
the sides. You can control how that padding is distributed with
this option. Using a value of center means the cell area will be
placed centrally. A value of top-left means the padding will be on
only the bottom and right edges.
#+begin_src conf
placement_strategy center
#+end_src

Hide the window decorations (title-bar and window borders). Whether
this works and exactly what effect it has depends on the window
manager/operating system.
#+begin_src conf
hide_window_decorations no
#+end_src
** Tab bar
The tab bar style, can be one of: fade, separator, powerline, or
hidden. In the fade style, each tab's edges fade into the
background color, in the separator style, tabs are separated by a
configurable separator, and the powerline shows the tabs as a
continuous line.
#+begin_src conf
tab_bar_style powerline
#+end_src

The separator between tabs in the tab bar when using separator as
the tab_bar_style.
#+begin_src conf
tab_separator " "
#+end_src
** Advanced
Allow other programs to control kitty. If you turn this on other
programs can control all aspects of kitty, including sending text
to kitty windows, opening new windows, closing windows, reading the
content of windows, etc.  Note that this even works over ssh
connections. You can chose to either allow any program running
within kitty to control it, with yes or only programs that connect
to the socket specified with the kitty --listen-on command line
option, if you use the value socket-only. The latter is useful if
you want to prevent programs running on a remote computer over ssh
from controlling kitty.
#+begin_src conf
allow_remote_control no
#+end_src

Allow programs running in kitty to read and write from the
clipboard. You can control exactly which actions are allowed. The
set of possible actions is: write-clipboard read-clipboard write-
primary read-primary. You can additionally specify no-append to
disable kitty's protocol extension for clipboard concatenation. The
default is to allow writing to the clipboard and primary selection
with concatenation enabled. Note that enabling the read
functionality is a security risk as it means that any program, even
one running on a remote server via SSH can read your clipboard.
#+begin_src conf
clipboard_control write-clipboard write-primary no-append
#+end_src

The value of the TERM environment variable to set. Changing this
can break many terminal programs, only change it if you know what
you are doing, not because you read some advice on Stack Overflow
to change it. The TERM variable is used by various programs to get
information about the capabilities and behavior of the terminal. If
you change it, depending on what programs you run, and how
different the terminal you are changing it to is, various things
from key-presses, to colors, to various advanced features may not
work.
#+begin_src conf
term xterm-kitty
#+end_src
** OS specific settings
*** macOS
Use the option key as an alt key. With this set to no, kitty will
use the macOS native Option+Key = unicode character behavior. This
will break any Alt+key keyboard shortcuts in your terminal
programs, but you can use the macOS unicode input technique. You
can use the values: left, right, or both to use only the left,
right or both Option keys as Alt, instead.
#+begin_src conf
macos_option_as_alt yes
#+end_src

Draw an extra border around the font with the given width, to
increase legibility at small font sizes. For example, a value of
0.75 will result in rendering that looks similar to sub-pixel
antialiasing at common font sizes.
#+begin_src conf
macos_thicken_font 0.3
#+end_src
** Key bindings
Change font size.
#+begin_src conf
map ctrl+shift+equal     change_font_size current +1.0
map ctrl+shift+minus     change_font_size current -1.0
map ctrl+shift+0         change_font_size current 0
#+end_src
** Theme
#+begin_src conf
include ./modus-operandi.conf
#+end_src
*** Modus Operandi
#+begin_src conf :tangle ~/.config/kitty/modus-operandi.conf
cursor #4a484d
cursor_text_color #ffffff
url_color #1d3ccf

active_border_color #5e4b4f
inactive_border_color #efefef
bell_border_color #8a3600

active_tab_foreground #005d26
active_tab_background #efefef
inactive_tab_foreground #5e4b4f
inactive_tab_background #ffffff

foreground #000000
background #ffffff
selection_foreground #ffffff
selection_background #4a484d

color0 #000000
color1 #a60000
color2 #005e00
color3 #813e00
color4 #0031a9
color5 #721045
color6 #00538b
color7 #bfbfbf
color8 #595959
color9 #972500
color10 #315b00
color11 #70480f
color12 #2544bb
color13 #5317ac
color14 #005a5f
color15 #ffffff
#+end_src
*** Modus Vivendi
#+begin_src conf :tangle ~/.config/kitty/modus-vivendi.conf
foreground  #ffffff
background  #000000

## cursor
cursor  #ffffff
cursor_text_color  #000000

## black
color8  #555555
color0  #222222

## red
color9  #ffa0a0
color1  #fb6859

## green
color10  #88cf88
color2   #00fc50

## yellow
color11  #d2b580
color3   #ffdd00

## blue
color12  #92baff
color4   #00a2ff

## magenta
color13  #e0b2d6
color5   #ff8bd4

## cyan
color14  #a0bfdf
color6   #30ffc0

## white
color15  #ffffff
color7   #dddddd

## Tabs
active_tab_foreground  #5ac3cf
active_tab_background  #0e0e0e
inactive_tab_foreground  #ffffff
inactive_tab_background  #3d3d3d
#+end_src
