gui:
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
git:
  parseEmoji: true
  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  diffRenderers:
    - type: extDiff
      name: difftastic
      command: difft --color=always --display=side-by-side --context={{diffContext}}
    - type: stdinFilter
      name: delta
      command: delta --paging=never
os:
  editPreset: "zed"
