[language-server.ruby-lsp]
command = "ruby-lsp"

[[language]]
name = "ruby"
scope = "source.rb"
injection-regex = "ruby"
roots = ["Gemfile", ".git"]
auto-format = true
language-servers = ["ruby-lsp", "solargraph"]
