#!/usr/bin/env fish

# start requried apps and services {{{
xlayoutdisplay -q

nm-applet --indicator &
blueman-applet &
flameshot &
udiskie -At &
~/.fehbg
xsetroot -cursor_name left_ptr &
sxhkd &
picom -b --experimental-backends &
~/.config/polybar/run.sh
dunst &

# Stop screen from going blank
xset s off
xset -dpms
xset s noblank

# Hide Cursor when typing
xbanish &

# Faster key repeat and delay
xset r rate 210 40
# }}}

# colors {{
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
# }}}

# configuration {{{
bspc monitor -d 1 2 3 4 5 6 7 8 9

# and split ratio
bspc config split_ratio 0.50

# borders and gaps
bspc config border_width 1
bspc config window_gap 0

# but not for monocle
bspc config borderless_monocle true
bspc config gapless_monocle true

# focus window under cursor
bspc config focus_follows_pointer true

# floating windows
bspc rule -r '*'

bspc rule -a mpv state=floating focus=on
bspc rule -a feh state=floating focus=on
bspc rule -a kitty:floating state=floating focus=on
bspc rule -a Emacs split_ratio=0.28 state=tiled
bspc rule -a Firefox split_ratio=0.32
bspc rule -a '*:scratch' state=floating sticky=on center=on border=off rectangle=1000x800+0+0

# Extra padding for polybar
bspc config -m primary top_padding 0
bspc config -m primary bottom_padding 34
# }}}
