#!/usr/bin/env fish

# load colors
set DIR (dirname (status --current-filename))
source $DIR/colors.fish

# set shell for keyboard daemon (should be bash)
set -x SXHKD_SHELL (which bash)

#
# required daemons
#

# run keyboard daemon
sxhkd &

# start compositor
picom -b --experimental-backends

# polybar
polybar base &

# configuration {{{
bspc monitor -d 1 2 3 4 5 6 7 8 9

# and split ratio
bspc config split_ratio 0.50

# borders and gaps
bspc config border_width 2
bspc config window_gap 8

# colors

bspc config normal_border_color $background
bspc config active_border_color $foreground
bspc config focused_border_color $color5
bspc config presel_feedback_color $color1

# but not for monocle
bspc config borderless_monocle true
bspc config gapless_monocle true

# focus window under cursor
bspc config focus_follows_pointer true

# floating windows
bspc rule -a mpv state=floating focus=on
bspc rule -a feh state=floating focus=on
bspc rule -a kitty:floating state=floating focus=on
bspc rule -a Emacs split_ratio=0.28 state=tiled
bspc rule -a Firefox split_ratio=0.32

bspc rule -r '*'
# }}}
